sounds:
  player-join-example:
    regex: '^(.*)(?:joined the game)$' #Example: https://regex101.com/r/v0umCZ/1
    sound: 'entity.itemframe.place'
    volume: 1.0
    pitch: 1.0
  player-leave-example:
    regex: '^(.*)(?:left the game)$'
    sound: 'entity.itemframe.break'
    volume: 1.0
    pitch: 1.0
